# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosUtilDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosUtilDemo
  pod 'SnapKit'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'Kingfisher', '~> 7.0'  # 添加 Kingfisher 依赖

end
